apiVersion: apps/v1
kind: StatefulSet
metadata:
  creationTimestamp: "2023-10-21T12:17:06Z"
  generation: 1
  labels:
    app: example-solrcloud-zookeeper
    app.kubernetes.io/instance: example-solr
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: solr
    app.kubernetes.io/version: 8.11.1
    helm.sh/chart: solr-0.8.0
    owner-rv: "1698546"
    release: example-solrcloud-zookeeper
    solr-cloud: example
    technology: zookeeper
  name: example-solrcloud-zookeeper
  namespace: default
  ownerReferences:
  - apiVersion: zookeeper.pravega.io/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: ZookeeperCluster
    name: example-solrcloud-zookeeper
    uid: 3bde4a92-70b0-4d6c-a585-6b01b47ceaa5
  resourceVersion: "1698598"
  uid: d722fb16-ea39-4a4d-a29b-852b61bc6493
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  podManagementPolicy: OrderedReady
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: example-solrcloud-zookeeper
  serviceName: example-solrcloud-zookeeper-headless
  template:
    metadata:
      creationTimestamp: null
      generateName: example-solrcloud-zookeeper
      labels:
        app: example-solrcloud-zookeeper
        app.kubernetes.io/instance: example-solr
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: solr
        app.kubernetes.io/version: 8.11.1
        helm.sh/chart: solr-0.8.0
        kind: ZookeeperMember
        release: example-solrcloud-zookeeper
        solr-cloud: example
        technology: zookeeper
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - example-solrcloud-zookeeper
              topologyKey: kubernetes.io/hostname
            weight: 20
      containers:
      - command:
        - /usr/local/bin/zookeeperStart.sh
        env:
        - name: ENVOY_SIDECAR_STATUS
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.annotations['sidecar.istio.io/status']
        image: pravega/zookeeper:0.2.14
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command:
              - zookeeperTeardown.sh
        livenessProbe:
          exec:
            command:
            - zookeeperLive.sh
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        name: zookeeper
        ports:
        - containerPort: 2181
          name: client
          protocol: TCP
        - containerPort: 2888
          name: quorum
          protocol: TCP
        - containerPort: 3888
          name: leader-election
          protocol: TCP
        - containerPort: 7000
          name: metrics
          protocol: TCP
        - containerPort: 8080
          name: admin-server
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - zookeeperReady.sh
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data
          name: data
        - mountPath: /conf
          name: conf
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: default
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: data
      - configMap:
          defaultMode: 420
          name: example-solrcloud-zookeeper-configmap
        name: conf
  updateStrategy:
    type: RollingUpdate
status:
  availableReplicas: 3
  collisionCount: 0
  currentReplicas: 3
  currentRevision: example-solrcloud-zookeeper-d9c6b65c4
  observedGeneration: 1
  readyReplicas: 3
  replicas: 3
  updateRevision: example-solrcloud-zookeeper-d9c6b65c4
  updatedReplicas: 3
