apiVersion: v1
data:
  # env.sh: |
  #   #!/usr/bin/env bash

  #   DOMAIN=example-solrcloud-zookeeper-headless.default.svc.cluster.local
  #   QUORUM_PORT=2888
  #   LEADER_PORT=3888
  #   CLIENT_HOST=example-solrcloud-zookeeper-client
  #   CLIENT_PORT=2181
  #   ADMIN_SERVER_HOST=example-solrcloud-zookeeper-admin-server
  #   ADMIN_SERVER_PORT=8080
  #   CLUSTER_NAME=example-solrcloud-zookeeper
  #   CLUSTER_SIZE=3
  # log4j-quiet.properties: |
  #   log4j.rootLogger=ERROR, CONSOLE
  #   log4j.appender.CONSOLE=org.apache.log4j.ConsoleAppender
  #   log4j.appender.CONSOLE.Threshold=ERROR
  #   log4j.appender.CONSOLE.layout=org.apache.log4j.PatternLayout
  #   log4j.appender.CONSOLE.layout.ConversionPattern=%d{ISO8601} [myid:%X{myid}] - %-5p [%t:%C{1}@%L] - %m%n
  # log4j.properties: |
  #   zookeeper.root.logger=CONSOLE
  #   zookeeper.console.threshold=INFO
  #   log4j.rootLogger=${zookeeper.root.logger}
  #   log4j.appender.CONSOLE=org.apache.log4j.ConsoleAppender
  #   log4j.appender.CONSOLE.Threshold=${zookeeper.console.threshold}
  #   log4j.appender.CONSOLE.layout=org.apache.log4j.PatternLayout
  #   log4j.appender.CONSOLE.layout.ConversionPattern=%d{ISO8601} [myid:%X{myid}] - %-5p [%t:%C{1}@%L] - %m%n
  zoo.cfg: |
    dataDir=/data
    dataLogDir=/datalog
    tickTime=2000
    initLimit=5
    syncLimit=2
    autopurge.snapRetainCount=3
    autopurge.purgeInterval=0
    maxClientCnxns=60
    standaloneEnabled=true
    admin.enableServer=true
    server.1=zookeeper-0.zookeeper:2888:3888;2181

kind: ConfigMap
metadata:
  name: zoo-config
