apiVersion: v1
data:
  env.sh: |
    #!/usr/bin/env bash

    DOMAIN=example-solrcloud-zookeeper-headless.default.svc.cluster.local
    QUORUM_PORT=2888
    LEADER_PORT=3888
    CLIENT_HOST=example-solrcloud-zookeeper-client
    CLIENT_PORT=2181
    ADMIN_SERVER_HOST=example-solrcloud-zookeeper-admin-server
    ADMIN_SERVER_PORT=8080
    CLUSTER_NAME=example-solrcloud-zookeeper
    CLUSTER_SIZE=3
  log4j-quiet.properties: |
    log4j.rootLogger=ERROR, CONSOLE
    log4j.appender.CONSOLE=org.apache.log4j.ConsoleAppender
    log4j.appender.CONSOLE.Threshold=ERROR
    log4j.appender.CONSOLE.layout=org.apache.log4j.PatternLayout
    log4j.appender.CONSOLE.layout.ConversionPattern=%d{ISO8601} [myid:%X{myid}] - %-5p [%t:%C{1}@%L] - %m%n
  log4j.properties: |
    zookeeper.root.logger=CONSOLE
    zookeeper.console.threshold=INFO
    log4j.rootLogger=${zookeeper.root.logger}
    log4j.appender.CONSOLE=org.apache.log4j.ConsoleAppender
    log4j.appender.CONSOLE.Threshold=${zookeeper.console.threshold}
    log4j.appender.CONSOLE.layout=org.apache.log4j.PatternLayout
    log4j.appender.CONSOLE.layout.ConversionPattern=%d{ISO8601} [myid:%X{myid}] - %-5p [%t:%C{1}@%L] - %m%n
  zoo.cfg: |
    4lw.commands.whitelist=cons, envi, conf, crst, srvr, stat, mntr, ruok
    dataDir=/data
    standaloneEnabled=false
    reconfigEnabled=true
    skipACL=yes
    metricsProvider.className=org.apache.zookeeper.metrics.prometheus.PrometheusMetricsProvider
    metricsProvider.httpPort=7000
    metricsProvider.exportJvmInfo=true
    initLimit=10
    syncLimit=2
    tickTime=2000
    globalOutstandingLimit=1000
    preAllocSize=65536
    snapCount=10000
    commitLogCount=500
    snapSizeLimitInKb=4194304
    maxCnxns=0
    maxClientCnxns=60
    minSessionTimeout=4000
    maxSessionTimeout=40000
    autopurge.snapRetainCount=3
    autopurge.purgeInterval=1
    quorumListenOnAllIPs=false
    admin.serverPort=8080
    dynamicConfigFile=/data/zoo.cfg.dynamic
kind: ConfigMap
metadata:
  creationTimestamp: "2023-10-21T12:17:06Z"
  labels:
    app: example-solrcloud-zookeeper
    app.kubernetes.io/instance: example-solr
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: solr
    app.kubernetes.io/version: 8.11.1
    helm.sh/chart: solr-0.8.0
    release: example-solrcloud-zookeeper
    solr-cloud: example
    technology: zookeeper
  name: example-solrcloud-zookeeper-configmap
  namespace: default
  ownerReferences:
  - apiVersion: zookeeper.pravega.io/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: ZookeeperCluster
    name: example-solrcloud-zookeeper
    uid: 3bde4a92-70b0-4d6c-a585-6b01b47ceaa5
  resourceVersion: "1698088"
  uid: 5e4ac3d4-8211-4347-81f1-dcc42dad7085
