apiVersion: v1
data:
  solr.xml: "<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\n<solr>\n  <str name=\"sharedLib\">${solr.sharedLib:},/opt/solr/contrib/jaegertracer-configurator/lib,/opt/solr/contrib/ltr/lib,/opt/solr/dist</str>\n
    \ <solrcloud>\n    <str name=\"host\">${host:}</str>\n    <int name=\"hostPort\">${solr.port.advertise:80}</int>\n
    \   <str name=\"hostContext\">${hostContext:solr}</str>\n    <bool name=\"genericCoreNodeNames\">${genericCoreNodeNames:true}</bool>\n
    \   <int name=\"zkClientTimeout\">${zkClientTimeout:30000}</int>\n    <int name=\"distribUpdateSoTimeout\">${distribUpdateSoTimeout:600000}</int>\n
    \   <int name=\"distribUpdateConnTimeout\">${distribUpdateConnTimeout:60000}</int>\n
    \   <str name=\"zkCredentialsProvider\">${zkCredentialsProvider:org.apache.solr.common.cloud.DefaultZkCredentialsProvider}</str>\n
    \   <str name=\"zkACLProvider\">${zkACLProvider:org.apache.solr.common.cloud.DefaultZkACLProvider}</str>\n
    \ </solrcloud>\n  <shardHandlerFactory name=\"shardHandlerFactory\"\n    class=\"HttpShardHandlerFactory\">\n
    \   <int name=\"socketTimeout\">${socketTimeout:600000}</int>\n    <int name=\"connTimeout\">${connTimeout:60000}</int>\n
    \ </shardHandlerFactory>\n  <int name=\"maxBooleanClauses\">${solr.max.booleanClauses:1024}</int>\n
    \ <str name=\"allowPaths\">${solr.allowPaths:}</str>\n  <metrics enabled=\"${metricsEnabled:true}\"/>\n
    \ \n</solr>\n"
kind: ConfigMap
metadata:
  creationTimestamp: "2023-10-30T07:03:21Z"
  labels:
    solr-cloud: example
  name: example-solrcloud-configmap
  namespace: default
  ownerReferences:
  - apiVersion: solr.apache.org/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: SolrCloud
    name: example
    uid: 5cb14ad0-b1f6-4ab0-aaf7-ade5bb31e9dd
  resourceVersion: "7821"
  uid: 8e170514-248b-4dd4-90ce-12eb11bbf98b