apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-10-30T10:20:18Z"
  labels:
    service-type: headless
    solr-cloud: example
  name: example-solrcloud-headless
  namespace: default
  ownerReferences:
  - apiVersion: solr.apache.org/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: SolrCloud
    name: example
    uid: 226de221-7a8f-423f-9fea-1c443bd764f8
  resourceVersion: "36422"
  uid: a51627be-8d41-437e-b926-599b2646c468
spec:
  clusterIP: None
  clusterIPs:
  - None
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: solr-client
    port: 8983
    protocol: TCP
    targetPort: solr-client
  publishNotReadyAddresses: true
  selector:
    solr-cloud: example
    technology: solr-cloud
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}