apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-10-30T07:03:21Z"
  labels:
    app: example-solrcloud-zookeeper
    headless: "false"
    owner-rv: "7811"
    release: example-solrcloud-zookeeper
    solr-cloud: example
    technology: zookeeper
  name: example-solrcloud-zookeeper-admin-server
  namespace: default
  ownerReferences:
  - apiVersion: zookeeper.pravega.io/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: ZookeeperCluster
    name: example-solrcloud-zookeeper
    uid: fa97b2dd-081c-4315-bd7d-9b6221cd8d02
  resourceVersion: "7833"
  uid: 3dee1549-d46b-4007-bc76-43cf794ddc22
spec:
  clusterIP: 10.128.176.147
  clusterIPs:
  - 10.128.176.147
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: tcp-admin-server
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: example-solrcloud-zookeeper
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
