apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-10-30T07:03:21Z"
  labels:
    app: example-solrcloud-zookeeper
    headless: "true"
    owner-rv: "7811"
    release: example-solrcloud-zookeeper
    solr-cloud: example
    technology: zookeeper
  name: example-solrcloud-zookeeper-headless
  namespace: default
  ownerReferences:
  - apiVersion: zookeeper.pravega.io/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: ZookeeperCluster
    name: example-solrcloud-zookeeper
    uid: fa97b2dd-081c-4315-bd7d-9b6221cd8d02
  resourceVersion: "7827"
  uid: 90ddc856-7839-4a8c-972b-88ef33e4d56b
spec:
  clusterIP: None
  clusterIPs:
  - None
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: tcp-client
    port: 2181
    protocol: TCP
    targetPort: 2181
  - name: tcp-quorum
    port: 2888
    protocol: TCP
    targetPort: 2888
  - name: tcp-leader-election
    port: 3888
    protocol: TCP
    targetPort: 3888
  - name: tcp-metrics
    port: 7000
    protocol: TCP
    targetPort: 7000
  - name: tcp-admin-server
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: example-solrcloud-zookeeper
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
