apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-10-30T07:03:21Z"
  labels:
    service-type: common
    solr-cloud: example
  name: example-solrcloud-common
  namespace: default
  ownerReferences:
  - apiVersion: solr.apache.org/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: SolrCloud
    name: example
    uid: 5cb14ad0-b1f6-4ab0-aaf7-ade5bb31e9dd
  resourceVersion: "7814"
  uid: cf9c1fb1-1e44-468a-b185-ef967e8189bb
spec:
  clusterIP: 10.128.138.234
  clusterIPs:
  - 10.128.138.234
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: solr-client
    port: 80
    protocol: TCP
    targetPort: solr-client
  selector:
    solr-cloud: example
    technology: solr-cloud
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
